steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build dependencies'
    args: [ 'build', '-f', 'Dockerfile.dev', '-t', 'gcr.io/$PROJECT_ID/simple-react-app-dependencies:$SHORT_SHA', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Run unit tests from dependencies'
    args: ['run', 'gcr.io/$PROJECT_ID/simple-react-app-dependencies:$SHORT_SHA', 'npm', 'run', 'test:ci']
    waitFor: ['Build dependencies']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build production image'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/simple-react-app:$SHORT_SHA', '.' ]

images: ['gcr.io/$PROJECT_ID/simple-react-app:$SHORT_SHA']