steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/simple-react-app/frontend:0.0.1', '.' ]
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/simple-react-app/frontend:0.0.1'