steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build dependencies'
    args: [ 'build', '--target', 'dependencies', '-t', 'gcr.io/$PROJECT_ID/simple-react-app-dependencies:$SHORT_SHA', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Run unit tests from dependencies'
    args: ['run', 'gcr.io/$PROJECT_ID/simple-react-app-dependencies:$SHORT_SHA', 'npm', 'run', 'test:ci']
    waitFor: ['Build dependencies']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build production image'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/simple-react-app:$SHORT_SHA', '.' ]

  - name: ubuntu
    id: 'Updating Deployment with built image'
    args: ['bash','-c','sed -i "s,REACT_IMAGE_NAME,gcr.io/$PROJECT_ID/simple-react-app:$SHORT_SHA," deployment.yaml']
    waitFor: ['Build production image']

  # Deploy container image to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: 'Deploy to Kubernetes cluster'
    args:
      - run
      - --filename=k8s
      - --image=gcr.io/$PROJECT_ID/simple-react-app:$SHORT_SHA
      - --location=${_CLOUDSDK_COMPUTE_ZONE}
      - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
    waitFor: ['Updating Deployment with built image']

images: ['gcr.io/$PROJECT_ID/simple-react-app:$SHORT_SHA']