version: '3.8'
services:
  frontend:
    build: 
      context: .
      target: dependencies
    container_name: frontend-dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app