apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-react-app
  template:
    metadata:
      labels:
        app: simple-react-app
    spec:
      containers:
        - name: simple-react-app
          image: 'gcr.io/learn-gcloud-build-123/simple-react-app:latest'
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: simple-react-app
  labels:
    run: simple-react-app
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: simple-react-app
  type: LoadBalancer

# NodePort service for local development only
---
apiVersion: v1
kind: Service
metadata:
  name: entrypoint
spec:
  type: NodePort
  selector:
    app: simple-react-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001